export const menuArray = [
	{
		name: "Pizza",
		icon: "pizza.png",
		toppings: ["pepperoni, mushroom, cheese"],
		price: 14,
		id: 0,
	},
	{
		name: "Burger",
		icon: "burger.png",
		toppings: ["bacon, cheese, tomato, pickles, lettuce"],
		price: 12,
		id: 1,
	},
	{
		name: "Taco",
		icon: "taco.png",
		toppings: ["beef, brown rice, black beans, cheese, sour cream"],
		price: 2,
		id: 2,
	},
	{
		name: "Hotdog",
		icon: "hotdog.png",
		toppings: ["ketchup, mustard, relish"],
		price: 4,
		id: 3,
	},
	{
		name: "Corndog",
		icon: "corndog.png",
		toppings: ["ketchup, mustard"],
		price: 3,
		id: 4,
	},
	{
		name: "Chicken Wrap",
		icon: "kebab.png",
		toppings: ["chicken, bacon, lettuce, cheese, tomato"],
		price: 10,
		id: 5,
	},
	{
		name: "Fries",
		icon: "french-fries.png",
		toppings: ["ketchup, bbq sauce, honey mustard"],
		price: 2,
		id: 6,
	},
	{
		name: "Beer",
		icon: "beer.png",
		toppings: [
			"Budweiser, Heineken, Miller Lite, Stella Artois, Michelob Ultra, Corona",
		],
		price: 5,
		id: 7,
	},
	{
		name: "Soda",
		icon: "soda.png",
		toppings: ["Dr.Pepper, Coke, Pepsi, Sprite, Mountain Dew"],
		price: 2,
		id: 8,
	},
	{
		name: "Ice Cream",
		icon: "ice-cream.png",
		toppings: ["vanilla, chocolate, pecan"],
		price: 4,
		id: 9,
	},
];
